In [4]:
#SquareRoot of Number

number = float(input("Enter a number: "))
sqrt = number ** 0.5
print("Square Root:", sqrt)

Enter a number: 121
Square Root: 11.0


In [5]:
#Solve Quadratic Equation

import cmath
print("The Quadratic Equation is of form ax2 + bx+ c\n")  
a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))
c = int(input("Enter the value of c: "))
  
# Computing the Discriminat value
D = (b**2) - (4*a*c)
  
# find two results
root1 = (-b - cmath.sqrt(D))/(2 * a)
root2 = (-b + cmath.sqrt(D))/(2 * a)
  
# printing the results
print("The roots are: ")
print(root1)
print(root2)

The Quadratic Equation is of form ax2 + bx+ c

Enter the value of a: 2
Enter the value of b: 4
Enter the value of c: 6
The roots are: 
(-1-1.4142135623730951j)
(-1+1.4142135623730951j)


In [8]:
#Solve Quadratic Equation

print("Equation: ax^2 + bx + c ")
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
d=b**2-4*a*c
d1=d**0.5
if(d<0):
    print("The roots are imaginary. ")
else:
    r1=(-b+d1)/2*a
    r2=(-b-d1)/2*a
    print("The first root: ",round(r1,2))
    print("The second root: ",round(r2,2))

Equation: ax^2 + bx + c 
Enter a: 1
Enter b: -7
Enter c: 10
The first root:  5.0
The second root:  2.0


In [9]:
#Swap 2 variables

x = input('Enter value of x: ')
y = input('Enter value of y: ')

# create a temporary variable and swap the values
temp = x
x = y
y = temp

print('The value of x after swapping: {}'.format(x))
print('The value of y after swapping: {}'.format(y))

Enter value of x: 7
Enter value of y: 11
The value of x after swapping: 11
The value of y after swapping: 7


In [10]:
#Swap 2 variables

x = input('Enter value of x: ')
y = input('Enter value of y: ')

x, y = y, x
print("x =", x)
print("y =", y)

Enter value of x: 7
Enter value of y: 11
x = 11
y = 7


In [11]:
#To check Armstrong Number

num = int(input("Enter a number: "))
# initialize sum
sum = 0
# find the sum of the cube of each digit
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10

# display the result
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

Enter a number: 153
153 is an Armstrong number


In [1]:
# Python program to find H.C.F of two numbers


def gcd(a, b):
    # Everything divides 0
    if (a == 0):
        return b
    if (b == 0):
        return a
  
    # base case
    if (a == b):
        return a
  
    # a is greater
    if (a > b):
        return gcd(a-b, b)
    return gcd(a, b-a)
  
# Driver program to test above function
a = float(input('Enter value of x: '))
b = float(input('Enter value of y: '))
if(gcd(a, b)):
    print('GCD of', a, 'and', b, 'is', gcd(a, b))
else:
    print('not found')

Enter value of x: 54
Enter value of y: 24
GCD of 54.0 and 24.0 is 6.0


In [23]:
# Python program to find H.C.F of two numbers

import math
a = int(input('Enter value of x: '))
b = int(input('Enter value of y: '))

print("GCD of ",a,"and ",b,"is: ",math.gcd(a,b))

Enter value of x: 60
Enter value of y: 48
GCD of  60 and  48 is:  12


In [24]:
# Python program to find L.C.M of two numbers

import math
a = int(input('Enter value of x: '))
b = int(input('Enter value of y: '))

print("GCD of ",a,"and ",b,"is: ",math.lcm(a,b))

Enter value of x: 54
Enter value of y: 24
GCD of  54 and  24 is:  216


In [4]:
# Program to transpose a matrix 

import numpy 
matrix=[[1,2,3],
        [4,5,6],
        [4,6,9]]
print(matrix)
print("\n")
print(numpy.transpose(matrix)) #or just numpy.T(matrix)

[[1, 2, 3], [4, 5, 6], [4, 6, 9]]


[[1 4 4]
 [2 5 6]
 [3 6 9]]


In [5]:
# Program to transpose a matrix using a nested loop

''' Program to transpose a matrix using list comprehension'''

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


In [20]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result= [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [21]:
#Sort a dictionary by value

dic= {"A": 13, "B": 7, "C": 0, "D": 10 }

sorted_dic= {}
sorted_values = sorted(dic, key=dic.get) 

print("Original dictionary: ",dic)

for i in sorted_values:
    sorted_dic[i] = dic[i]
print("Sorted dictionary: ", sorted_dic)


Original dictionary:  {'A': 13, 'B': 7, 'C': 0, 'D': 10}
Sorted dictionary:  {'C': 0, 'B': 7, 'D': 10, 'A': 13}


In [22]:
#Sort a dictionary by value

dt = {"A":90, "B":2, "C":3}

sorted_dt_value = sorted(dt.values())
print(dt)
print(sorted_dt_value)


{'A': 90, 'B': 2, 'C': 3}
[2, 3, 90]


In [5]:
#Convert string to datetime

from datetime import datetime
date_object = datetime.strptime('Jul 1 2014 2:43PM', '%b %d %Y %I:%M%p')
print(date_object)

2014-07-01 14:43:00


In [4]:
#Convert string to datetime

from dateutil import parser
date_time = parser.parse("Mar 11 2011 11:31AM")
print(date_time)
print(type(date_time))

2011-03-11 11:31:00
<class 'datetime.datetime'>


In [7]:
#Program to Reverse a Number

n=int(input("Enter number: "))
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10  #%
print("Reverse of the number:",rev)

Enter number: 711
Reverse of the number: 117


In [10]:
num=int(input("Enter Number: "))
power=int(input("Enter Power: "))
print("Power : ",pow(num,power))

Enter Number: 3
Enter Power: 2
Power :  9


In [11]:
base = 3
exponent = 4

result = 1

while exponent != 0:
    result *= base
    exponent-=1

print("Answer = " + str(result))

Answer = 81


In [12]:
#Countdown time

import time

def countdown(time_sec):
    while time_sec:
        mins, secs = divmod(time_sec, 60)
        timeformat = '{:02d}:{:02d}'.format(mins, secs)
        print(timeformat, end='\r')
        time.sleep(1)
        time_sec -= 1

    print("stop")

countdown(5)

stop1


In [14]:
import time
  
# define the countdown func.
def countdown(t):
    while t:
        mins, secs = divmod(t, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
    print('Fire in the hole!!')
  # input time in seconds
t = input("Enter the time in seconds: ")
  
# function call
countdown(int(t))

Enter the time in seconds: 5
Fire in the hole!!


In [19]:
# Program for converting bytes
# to string using decode()

data = b'hellloooo'

# display input
print('\nInput:')
print(data)
print(type(data))

# converting
output = data.decode()

# display output
print('\nOutput:')
print(output)
print(type(output))



Input:
b'hellloooo'
<class 'bytes'>

Output:
hellloooo
<class 'str'>


In [20]:
file1 = open("myfile.txt", "w")
L = ["This is Delhi \n", "This is Paris \n", "This is London"]
file1.writelines(L)
file1.close()
 
# Append-adds at last
file1 = open("myfile.txt", "a")  # append mode
file1.write("Today \n")
file1.close()
 
file1 = open("myfile.txt", "r")
print("Output of Readlines after appending")
print(file1.read())
print()
file1.close()

Output of Readlines after appending
This is Delhi 
This is Paris 
This is LondonToday 




In [21]:
# Python program to merge two files 
data = data2 = "" 
  
# Reading data from first file 
with open('file1.txt') as fp: 
    data = fp.read() 
with open('file2.txt') as fp: 
    data2 = fp.read() 
# Merging two files into one another file 
data += "\n"
data += data2 
with open ('file3.txt', 'w') as fp: 
    fp.write(data)